baseURL = 'https://yuki-asaka.github.io/hugo-example/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
proxy = "direct"
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

# multilingual
#[languages]
#[languages.en]
#languageName = 'English'
#contentDir = 'content'
#weight = 1

[params]
BookTheme = 'auto'
BookToC = true
#BookMenuBundle = '/menu'  # @deprecated override default menu bundle
BookSection = '/'
#BookSearch = false
